# Generated by Django 3.0.6 on 2020-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('about', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='myportfolio')),
            ],
            options={
                'verbose_name_plural': ' projects',
            },
        ),
    ]
