# Generated by Django 3.0.6 on 2020-11-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={},
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
