# Generated by Django 3.0.6 on 2020-11-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_auto_20201112_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='topicc',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
